-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:6eb828858b82f1c419325cbc55434cb5:a448263bad1c36feec6cec53b3a3329d:707faf395d8b70780d7fff40a24ea6f4$
-- 

return {
	texture = 'mainchar_pieces.png',
	frames = {
			{
				name = "baff.png",
				spriteColorRect = { x = 0, y = 0, width = 249, height = 89 },
				uvRect = { u0 = 0.00390625, v0 = 0.193359, u1 = 0.490234, v1 = 0.280273 },
				spriteSourceSize = { width = 249, height = 89 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "belt.png",
				spriteColorRect = { x = 0, y = 0, width = 47, height = 13 },
				uvRect = { u0 = 0.398438, v0 = 0.282227, u1 = 0.490234, v1 = 0.294922 },
				spriteSourceSize = { width = 47, height = 13 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "belt_away.png",
				spriteColorRect = { x = 0, y = 0, width = 47, height = 11 },
				uvRect = { u0 = 0.398438, v0 = 0.296875, u1 = 0.490234, v1 = 0.307617 },
				spriteSourceSize = { width = 47, height = 11 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "belt_away_180.png",
				spriteColorRect = { x = 0, y = 0, width = 64, height = 12 },
				uvRect = { u0 = 0.00390625, v0 = 0.986328, u1 = 0.128906, v1 = 0.998047 },
				spriteSourceSize = { width = 64, height = 12 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "belt_towards.png",
				spriteColorRect = { x = 0, y = 0, width = 53, height = 22 },
				uvRect = { u0 = 0.707031, v0 = 0.689453, u1 = 0.810547, v1 = 0.710938 },
				spriteSourceSize = { width = 53, height = 22 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "belt_towards_180.png",
				spriteColorRect = { x = 0, y = 0, width = 64, height = 12 },
				uvRect = { u0 = 0.132812, v0 = 0.986328, u1 = 0.257812, v1 = 0.998047 },
				spriteSourceSize = { width = 64, height = 12 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "boat_sideways.png",
				spriteColorRect = { x = 0, y = 0, width = 462, height = 92 },
				uvRect = { u0 = 0.00390625, v0 = 0.00195312, u1 = 0.90625, v1 = 0.0917969 },
				spriteSourceSize = { width = 462, height = 92 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "eyelid.png",
				spriteColorRect = { x = 0, y = 0, width = 10, height = 8 },
				uvRect = { u0 = 0.818359, v0 = 0.31543, u1 = 0.837891, v1 = 0.323242 },
				spriteSourceSize = { width = 10, height = 8 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "fishing_pole.png",
				spriteColorRect = { x = 0, y = 0, width = 71, height = 346 },
				uvRect = { u0 = 0.814453, v0 = 0.646484, u1 = 0.953125, v1 = 0.984375 },
				spriteSourceSize = { width = 71, height = 346 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "fishing_pole_closed.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 148 },
				uvRect = { u0 = 0.623047, v0 = 0.823242, u1 = 0.669922, v1 = 0.967773 },
				spriteSourceSize = { width = 24, height = 148 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "flame1.png",
				spriteColorRect = { x = 0, y = 0, width = 23, height = 30 },
				uvRect = { u0 = 0.0527344, v0 = 0.813477, u1 = 0.0976562, v1 = 0.842773 },
				spriteSourceSize = { width = 23, height = 30 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "flame2.png",
				spriteColorRect = { x = 0, y = 0, width = 23, height = 30 },
				uvRect = { u0 = 0.101562, v0 = 0.813477, u1 = 0.146484, v1 = 0.842773 },
				spriteSourceSize = { width = 23, height = 30 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "flame3.png",
				spriteColorRect = { x = 0, y = 0, width = 23, height = 30 },
				uvRect = { u0 = 0.150391, v0 = 0.813477, u1 = 0.195312, v1 = 0.842773 },
				spriteSourceSize = { width = 23, height = 30 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "flame4.png",
				spriteColorRect = { x = 0, y = 0, width = 23, height = 30 },
				uvRect = { u0 = 0.199219, v0 = 0.825195, u1 = 0.244141, v1 = 0.854492 },
				spriteSourceSize = { width = 23, height = 30 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "flame5.png",
				spriteColorRect = { x = 0, y = 0, width = 23, height = 30 },
				uvRect = { u0 = 0.0527344, v0 = 0.844727, u1 = 0.0976562, v1 = 0.874023 },
				spriteSourceSize = { width = 23, height = 30 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "flame6.png",
				spriteColorRect = { x = 0, y = 0, width = 23, height = 30 },
				uvRect = { u0 = 0.00390625, v0 = 0.845703, u1 = 0.0488281, v1 = 0.875 },
				spriteSourceSize = { width = 23, height = 30 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "flame7.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 30 },
				uvRect = { u0 = 0.207031, v0 = 0.793945, u1 = 0.253906, v1 = 0.823242 },
				spriteSourceSize = { width = 24, height = 30 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "flame8.png",
				spriteColorRect = { x = 0, y = 0, width = 23, height = 30 },
				uvRect = { u0 = 0.101562, v0 = 0.844727, u1 = 0.146484, v1 = 0.874023 },
				spriteSourceSize = { width = 23, height = 30 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "grass_foot.png",
				spriteColorRect = { x = 0, y = 0, width = 38, height = 43 },
				uvRect = { u0 = 0.910156, v0 = 0.237305, u1 = 0.984375, v1 = 0.279297 },
				spriteSourceSize = { width = 38, height = 43 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "grass_foot2.png",
				spriteColorRect = { x = 0, y = 0, width = 38, height = 43 },
				uvRect = { u0 = 0.910156, v0 = 0.28125, u1 = 0.984375, v1 = 0.323242 },
				spriteSourceSize = { width = 38, height = 43 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "head.png",
				spriteColorRect = { x = 0, y = 0, width = 55, height = 63 },
				uvRect = { u0 = 0.125, v0 = 0.692383, u1 = 0.232422, v1 = 0.753906 },
				spriteSourceSize = { width = 55, height = 63 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "head_away.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 57 },
				uvRect = { u0 = 0.105469, v0 = 0.755859, u1 = 0.203125, v1 = 0.811523 },
				spriteSourceSize = { width = 50, height = 57 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "head_away_180.png",
				spriteColorRect = { x = 0, y = 0, width = 43, height = 58 },
				uvRect = { u0 = 0.910156, v0 = 0.108398, u1 = 0.994141, v1 = 0.165039 },
				spriteSourceSize = { width = 43, height = 58 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "head_towards.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 60 },
				uvRect = { u0 = 0.00390625, v0 = 0.75293, u1 = 0.101562, v1 = 0.811523 },
				spriteSourceSize = { width = 50, height = 60 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "head_towards_180.png",
				spriteColorRect = { x = 0, y = 0, width = 42, height = 70 },
				uvRect = { u0 = 0.910156, v0 = 0.166992, u1 = 0.992188, v1 = 0.235352 },
				spriteSourceSize = { width = 42, height = 70 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "lasso.png",
				spriteColorRect = { x = 0, y = 0, width = 26, height = 51 },
				uvRect = { u0 = 0.492188, v0 = 0.467773, u1 = 0.542969, v1 = 0.517578 },
				spriteSourceSize = { width = 26, height = 51 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "left_arm_away.png",
				spriteColorRect = { x = 0, y = 0, width = 34, height = 48 },
				uvRect = { u0 = 0.398438, v0 = 0.609375, u1 = 0.464844, v1 = 0.65625 },
				spriteSourceSize = { width = 34, height = 48 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "left_arm_away_180.png",
				spriteColorRect = { x = 0, y = 0, width = 31, height = 47 },
				uvRect = { u0 = 0.726562, v0 = 0.923828, u1 = 0.787109, v1 = 0.969727 },
				spriteSourceSize = { width = 31, height = 47 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "left_arm_towards.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 42 },
				uvRect = { u0 = 0.617188, v0 = 0.710938, u1 = 0.664062, v1 = 0.751953 },
				spriteSourceSize = { width = 24, height = 42 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "left_arm_towards_180.png",
				spriteColorRect = { x = 0, y = 0, width = 31, height = 49 },
				uvRect = { u0 = 0.390625, v0 = 0.733398, u1 = 0.451172, v1 = 0.78125 },
				spriteSourceSize = { width = 31, height = 49 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "left_fist.png",
				spriteColorRect = { x = 0, y = 0, width = 23, height = 29 },
				uvRect = { u0 = 0.617188, v0 = 0.969727, u1 = 0.662109, v1 = 0.998047 },
				spriteSourceSize = { width = 23, height = 29 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "left_foot_towards.png",
				spriteColorRect = { x = 0, y = 0, width = 80, height = 110 },
				uvRect = { u0 = 0.546875, v0 = 0.601562, u1 = 0.703125, v1 = 0.708984 },
				spriteSourceSize = { width = 80, height = 110 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "left_hand.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 43 },
				uvRect = { u0 = 0.521484, v0 = 0.710938, u1 = 0.568359, v1 = 0.75293 },
				spriteSourceSize = { width = 24, height = 43 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "left_hand_away.png",
				spriteColorRect = { x = 0, y = 0, width = 27, height = 52 },
				uvRect = { u0 = 0.494141, v0 = 0.302734, u1 = 0.546875, v1 = 0.353516 },
				spriteSourceSize = { width = 27, height = 52 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "left_hand_away_180.png",
				spriteColorRect = { x = 0, y = 0, width = 22, height = 55 },
				uvRect = { u0 = 0.150391, v0 = 0.844727, u1 = 0.193359, v1 = 0.898438 },
				spriteSourceSize = { width = 22, height = 55 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "left_hand_towards.png",
				spriteColorRect = { x = 0, y = 0, width = 27, height = 52 },
				uvRect = { u0 = 0.492188, v0 = 0.415039, u1 = 0.544922, v1 = 0.46582 },
				spriteSourceSize = { width = 27, height = 52 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "left_hand_towards_180.png",
				spriteColorRect = { x = 0, y = 0, width = 21, height = 42 },
				uvRect = { u0 = 0.623047, v0 = 0.753906, u1 = 0.664062, v1 = 0.794922 },
				spriteSourceSize = { width = 21, height = 42 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "left_leg_away.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 135 },
				uvRect = { u0 = 0.714844, v0 = 0.5, u1 = 0.8125, v1 = 0.631836 },
				spriteSourceSize = { width = 50, height = 135 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "left_leg_away_180.png",
				spriteColorRect = { x = 0, y = 0, width = 35, height = 104 },
				uvRect = { u0 = 0.474609, v0 = 0.519531, u1 = 0.542969, v1 = 0.621094 },
				spriteSourceSize = { width = 35, height = 104 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "left_leg_towards.png",
				spriteColorRect = { x = 0, y = 0, width = 80, height = 150 },
				uvRect = { u0 = 0.816406, v0 = 0.498047, u1 = 0.972656, v1 = 0.644531 },
				spriteSourceSize = { width = 80, height = 150 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "left_leg_towards_180.png",
				spriteColorRect = { x = 0, y = 0, width = 48, height = 105 },
				uvRect = { u0 = 0.519531, v0 = 0.867188, u1 = 0.613281, v1 = 0.969727 },
				spriteSourceSize = { width = 48, height = 105 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "left_shoulder_away_180.png",
				spriteColorRect = { x = 0, y = 0, width = 29, height = 62 },
				uvRect = { u0 = 0.494141, v0 = 0.193359, u1 = 0.550781, v1 = 0.253906 },
				spriteSourceSize = { width = 29, height = 62 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "left_shoulder_towards.png",
				spriteColorRect = { x = 0, y = 0, width = 35, height = 83 },
				uvRect = { u0 = 0.189453, v0 = 0.514648, u1 = 0.257812, v1 = 0.595703 },
				spriteSourceSize = { width = 35, height = 83 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "left_shoulder_towards_180.png",
				spriteColorRect = { x = 0, y = 0, width = 25, height = 65 },
				uvRect = { u0 = 0.673828, v0 = 0.923828, u1 = 0.722656, v1 = 0.987305 },
				spriteSourceSize = { width = 25, height = 65 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "left_thigh_away_180.png",
				spriteColorRect = { x = 0, y = 0, width = 46, height = 110 },
				uvRect = { u0 = 0.722656, v0 = 0.390625, u1 = 0.8125, v1 = 0.498047 },
				spriteSourceSize = { width = 46, height = 110 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "left_thigh_towards_180.png",
				spriteColorRect = { x = 0, y = 0, width = 43, height = 107 },
				uvRect = { u0 = 0.910156, v0 = 0.00195312, u1 = 0.994141, v1 = 0.106445 },
				spriteSourceSize = { width = 43, height = 107 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "oar_head.png",
				spriteColorRect = { x = 0, y = 0, width = 133, height = 100 },
				uvRect = { u0 = 0.554688, v0 = 0.108398, u1 = 0.814453, v1 = 0.206055 },
				spriteSourceSize = { width = 133, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pickaxe.png",
				spriteColorRect = { x = 0, y = 0, width = 125, height = 35 },
				uvRect = { u0 = 0.554688, v0 = 0.208008, u1 = 0.798828, v1 = 0.242188 },
				spriteSourceSize = { width = 125, height = 35 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "right_arm_away.png",
				spriteColorRect = { x = 0, y = 0, width = 53, height = 55 },
				uvRect = { u0 = 0.707031, v0 = 0.633789, u1 = 0.810547, v1 = 0.6875 },
				spriteSourceSize = { width = 53, height = 55 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "right_arm_away_180.png",
				spriteColorRect = { x = 0, y = 0, width = 31, height = 52 },
				uvRect = { u0 = 0.457031, v0 = 0.702148, u1 = 0.517578, v1 = 0.75293 },
				spriteSourceSize = { width = 31, height = 52 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "right_arm_towards.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 75 },
				uvRect = { u0 = 0.390625, v0 = 0.658203, u1 = 0.453125, v1 = 0.731445 },
				spriteSourceSize = { width = 32, height = 75 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "right_arm_towards_180.png",
				spriteColorRect = { x = 0, y = 0, width = 31, height = 60 },
				uvRect = { u0 = 0.753906, v0 = 0.330078, u1 = 0.814453, v1 = 0.388672 },
				spriteSourceSize = { width = 31, height = 60 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "right_fist.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 37 },
				uvRect = { u0 = 0.207031, v0 = 0.755859, u1 = 0.253906, v1 = 0.791992 },
				spriteSourceSize = { width = 24, height = 37 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "right_fist_away_180.png",
				spriteColorRect = { x = 0, y = 0, width = 20, height = 30 },
				uvRect = { u0 = 0.957031, v0 = 0.646484, u1 = 0.996094, v1 = 0.675781 },
				spriteSourceSize = { width = 20, height = 30 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "right_fist_towards_180.png",
				spriteColorRect = { x = 0, y = 0, width = 19, height = 24 },
				uvRect = { u0 = 0.957031, v0 = 0.734375, u1 = 0.994141, v1 = 0.757812 },
				spriteSourceSize = { width = 19, height = 24 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "right_foot_away.png",
				spriteColorRect = { x = 0, y = 0, width = 68, height = 109 },
				uvRect = { u0 = 0.261719, v0 = 0.514648, u1 = 0.394531, v1 = 0.621094 },
				spriteSourceSize = { width = 68, height = 109 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "right_foot_towards.png",
				spriteColorRect = { x = 0, y = 0, width = 70, height = 120 },
				uvRect = { u0 = 0.261719, v0 = 0.876953, u1 = 0.398438, v1 = 0.994141 },
				spriteSourceSize = { width = 70, height = 120 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "right_forearm.png",
				spriteColorRect = { x = 0, y = 0, width = 34, height = 50 },
				uvRect = { u0 = 0.398438, v0 = 0.558594, u1 = 0.464844, v1 = 0.607422 },
				spriteSourceSize = { width = 34, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "right_hand.png",
				spriteColorRect = { x = 0, y = 0, width = 28, height = 46 },
				uvRect = { u0 = 0.494141, v0 = 0.255859, u1 = 0.548828, v1 = 0.300781 },
				spriteSourceSize = { width = 28, height = 46 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "right_hand_away.png",
				spriteColorRect = { x = 0, y = 0, width = 30, height = 59 },
				uvRect = { u0 = 0.492188, v0 = 0.355469, u1 = 0.550781, v1 = 0.413086 },
				spriteSourceSize = { width = 30, height = 59 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "right_hand_away_180.png",
				spriteColorRect = { x = 0, y = 0, width = 19, height = 56 },
				uvRect = { u0 = 0.957031, v0 = 0.677734, u1 = 0.994141, v1 = 0.732422 },
				spriteSourceSize = { width = 19, height = 56 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "right_hand_towards_180.png",
				spriteColorRect = { x = 0, y = 0, width = 21, height = 43 },
				uvRect = { u0 = 0.572266, v0 = 0.710938, u1 = 0.613281, v1 = 0.75293 },
				spriteSourceSize = { width = 21, height = 43 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "right_leg.png",
				spriteColorRect = { x = 0, y = 0, width = 60, height = 113 },
				uvRect = { u0 = 0.501953, v0 = 0.754883, u1 = 0.619141, v1 = 0.865234 },
				spriteSourceSize = { width = 60, height = 113 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "right_leg_away.png",
				spriteColorRect = { x = 0, y = 0, width = 89, height = 175 },
				uvRect = { u0 = 0.818359, v0 = 0.325195, u1 = 0.992188, v1 = 0.496094 },
				spriteSourceSize = { width = 89, height = 175 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "right_leg_away_180.png",
				spriteColorRect = { x = 0, y = 0, width = 31, height = 86 },
				uvRect = { u0 = 0.753906, v0 = 0.244141, u1 = 0.814453, v1 = 0.328125 },
				spriteSourceSize = { width = 31, height = 86 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "right_leg_towards.png",
				spriteColorRect = { x = 0, y = 0, width = 60, height = 140 },
				uvRect = { u0 = 0.00390625, v0 = 0.614258, u1 = 0.121094, v1 = 0.750977 },
				spriteSourceSize = { width = 60, height = 140 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "right_leg_towards_180.png",
				spriteColorRect = { x = 0, y = 0, width = 38, height = 105 },
				uvRect = { u0 = 0.832031, v0 = 0.09375, u1 = 0.90625, v1 = 0.196289 },
				spriteSourceSize = { width = 38, height = 105 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "right_shoulder.png",
				spriteColorRect = { x = 0, y = 0, width = 35, height = 78 },
				uvRect = { u0 = 0.189453, v0 = 0.597656, u1 = 0.257812, v1 = 0.673828 },
				spriteSourceSize = { width = 35, height = 78 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "right_shoulder_away.png",
				spriteColorRect = { x = 0, y = 0, width = 55, height = 90 },
				uvRect = { u0 = 0.390625, v0 = 0.783203, u1 = 0.498047, v1 = 0.871094 },
				spriteSourceSize = { width = 55, height = 90 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "right_shoulder_away_180.png",
				spriteColorRect = { x = 0, y = 0, width = 24, height = 78 },
				uvRect = { u0 = 0.125, v0 = 0.614258, u1 = 0.171875, v1 = 0.69043 },
				spriteSourceSize = { width = 24, height = 78 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "right_shoulder_raised_away_180.png",
				spriteColorRect = { x = 0, y = 0, width = 23, height = 31 },
				uvRect = { u0 = 0.00390625, v0 = 0.813477, u1 = 0.0488281, v1 = 0.84375 },
				spriteSourceSize = { width = 23, height = 31 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "right_shoulder_towards.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 80 },
				uvRect = { u0 = 0.398438, v0 = 0.478516, u1 = 0.470703, v1 = 0.556641 },
				spriteSourceSize = { width = 37, height = 80 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "right_shoulder_towards_180.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 79 },
				uvRect = { u0 = 0.46875, v0 = 0.623047, u1 = 0.53125, v1 = 0.700195 },
				spriteSourceSize = { width = 32, height = 79 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "right_thigh.png",
				spriteColorRect = { x = 0, y = 0, width = 62, height = 101 },
				uvRect = { u0 = 0.673828, v0 = 0.823242, u1 = 0.794922, v1 = 0.921875 },
				spriteSourceSize = { width = 62, height = 101 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "right_thigh_away_180.png",
				spriteColorRect = { x = 0, y = 0, width = 45, height = 118 },
				uvRect = { u0 = 0.818359, v0 = 0.198242, u1 = 0.90625, v1 = 0.313477 },
				spriteSourceSize = { width = 45, height = 118 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "right_thigh_towards_180.png",
				spriteColorRect = { x = 0, y = 0, width = 58, height = 114 },
				uvRect = { u0 = 0.402344, v0 = 0.873047, u1 = 0.515625, v1 = 0.984375 },
				spriteSourceSize = { width = 58, height = 114 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "rope.png",
				spriteColorRect = { x = 0, y = 0, width = 18, height = 129 },
				uvRect = { u0 = 0.957031, v0 = 0.759766, u1 = 0.992188, v1 = 0.885742 },
				spriteSourceSize = { width = 18, height = 129 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "stick_without_oar.png",
				spriteColorRect = { x = 0, y = 0, width = 280, height = 100 },
				uvRect = { u0 = 0.00390625, v0 = 0.09375, u1 = 0.550781, v1 = 0.191406 },
				spriteSourceSize = { width = 280, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sword.png",
				spriteColorRect = { x = 0, y = 0, width = 140, height = 13 },
				uvRect = { u0 = 0.554688, v0 = 0.09375, u1 = 0.828125, v1 = 0.106445 },
				spriteSourceSize = { width = 140, height = 13 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "torch.png",
				spriteColorRect = { x = 0, y = 0, width = 46, height = 171 },
				uvRect = { u0 = 0.398438, v0 = 0.30957, u1 = 0.488281, v1 = 0.476562 },
				spriteSourceSize = { width = 46, height = 171 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "torso.png",
				spriteColorRect = { x = 0, y = 0, width = 64, height = 111 },
				uvRect = { u0 = 0.261719, v0 = 0.766602, u1 = 0.386719, v1 = 0.875 },
				spriteSourceSize = { width = 64, height = 111 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "torso_away.png",
				spriteColorRect = { x = 0, y = 0, width = 84, height = 120 },
				uvRect = { u0 = 0.554688, v0 = 0.363281, u1 = 0.71875, v1 = 0.480469 },
				spriteSourceSize = { width = 84, height = 120 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "torso_away_180.png",
				spriteColorRect = { x = 0, y = 0, width = 98, height = 117 },
				uvRect = { u0 = 0.203125, v0 = 0.282227, u1 = 0.394531, v1 = 0.396484 },
				spriteSourceSize = { width = 98, height = 117 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "torso_away_180_with_armor.png",
				spriteColorRect = { x = 0, y = 0, width = 98, height = 117 },
				uvRect = { u0 = 0.203125, v0 = 0.398438, u1 = 0.394531, v1 = 0.512695 },
				spriteSourceSize = { width = 98, height = 117 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "torso_away_with_armor.png",
				spriteColorRect = { x = 0, y = 0, width = 84, height = 120 },
				uvRect = { u0 = 0.546875, v0 = 0.482422, u1 = 0.710938, v1 = 0.599609 },
				spriteSourceSize = { width = 84, height = 120 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "torso_bend.png",
				spriteColorRect = { x = 0, y = 0, width = 64, height = 145 },
				uvRect = { u0 = 0.261719, v0 = 0.623047, u1 = 0.386719, v1 = 0.764648 },
				spriteSourceSize = { width = 64, height = 145 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "torso_towards.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 120 },
				uvRect = { u0 = 0.554688, v0 = 0.244141, u1 = 0.75, v1 = 0.361328 },
				spriteSourceSize = { width = 100, height = 120 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "torso_towards_180.png",
				spriteColorRect = { x = 0, y = 0, width = 93, height = 107 },
				uvRect = { u0 = 0.00390625, v0 = 0.401367, u1 = 0.185547, v1 = 0.505859 },
				spriteSourceSize = { width = 93, height = 107 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "torso_towards_180_with_armor.png",
				spriteColorRect = { x = 0, y = 0, width = 93, height = 107 },
				uvRect = { u0 = 0.00390625, v0 = 0.507812, u1 = 0.185547, v1 = 0.612305 },
				spriteSourceSize = { width = 93, height = 107 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "torso_towards_with_armor.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 120 },
				uvRect = { u0 = 0.00390625, v0 = 0.282227, u1 = 0.199219, v1 = 0.399414 },
				spriteSourceSize = { width = 100, height = 120 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "torso_with_armor.png",
				spriteColorRect = { x = 0, y = 0, width = 64, height = 111 },
				uvRect = { u0 = 0.667969, v0 = 0.712891, u1 = 0.792969, v1 = 0.821289 },
				spriteSourceSize = { width = 64, height = 111 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

